# site name
siteName: hojun
shortName: HJ


# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/honjun/ImageHosting/sina/006bYVyvgy1ftoufg1c8fj300g00g3yb.jpg
avatar: https://cdn.jsdelivr.net/gh/honjun/ImageHosting/sina/006bYVyvgy1ftand2qurdj303c03cdfv.jpg

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10


# your site build time or founded date
siteBuildingTime: 04/24/2017


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   技术: tech
   生活: live
   # 资源: resource

adsense:
  enable: true
  auto: true
  client_id: ca-pub-5634033670687375
  archive_id: 2605592596
  tags_id: 4259006495
  post_left_id: 9797686907
  post_right_id: 7335051380
  post_bottom_id: 8296902977

tocbot:
  contentSelector: .post-content
  scrollSmooth: true
  headingSelector: h1, h2, h3, h4, h5
  headingsOffset: 45
  scrollSmoothOffset: -45

# cover info config
coverTitle: hello ，stranger
coverDescription: 一个好奇的博客
sinaWb: https://weibo.com/5673857615/profile?topnav=1&wvr=6&is_all=1
facebook: 
qq: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes
github: https://github.com/honjun
bili: https://space.bilibili.com/271849279/#/
zhihu: https://github.com/honjun


# Git-pages server info
gitPageServerName: Github Pages
gitPageServerUrl: https://github.com/
codingPageServerName: Coding Pages
codingPageServerUrl: https://pages.coding.me