# site name
siteName: hojun
shortName: HJ


# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon and site master avatar
favicon: https://wx1.sinaimg.cn/large/006bYVyvgy1ftan8a9g6xj303c03cdfv.jpg
avatar: https://wx1.sinaimg.cn/large/006bYVyvgy1ftand2qurdj303c03cdfv.jpg

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10


# your site build time or founded date
siteBuildingTime: 04/24/2017


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   技术: tech
   生活: live
   # 资源: resource


# cover info config
coverTitle: hello ，stranger
coverDescription: 一个好奇的博客
sinaWb: https://weibo.com/5673857615/profile?topnav=1&wvr=6&is_all=1
facebook: 
qq: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes
github: https://github.com/honjun


# Git-pages server info
gitPageServerName: Github Pages
gitPageServerUrl: https://github.com/
codingPageServerName: Coding Pages
codingPageServerUrl: https://pages.coding.me